name: Deploy to WordPress.org
on:
#  push:
#    tags:
#      - "*"
    workflow_dispatch:
      inputs:
        dry-run:
          description: 'Run the deployment process without committing (DRY RUN).'
          default: true
        plugin-version:
          description: 'The plugin version i.e. 1.2.3'
          required: true
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

#      - name: Install dependencies
#        uses: php-actions/composer@v6
#        with:
#          version: 2

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        #uses: kresimir71/action-wordpress-plugin-deploy@develop
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          VERSION: ${{ inputs.plugin-version }}
        with:
          dry-run: ${{ inputs.dry-run }}
          
